import type { Metadata } from "next";
import { Silkscreen } from "next/font/google";
import { Rubik_Puddles } from "next/font/google";
import { Ultra } from "next/font/google";
import "./globals.css";

const ultra = Ultra({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-ultra",
});

const silkscreen = Silkscreen({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-silkscreen",
});

const rubikPuddles = Rubik_Puddles({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-rubik-puddles",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${silkscreen.variable} ${rubikPuddles.variable} ${ultra.variable}`}
    >
      <body className="font-serif">{children}</body>
    </html>
  );
}
